root/etc/cont-init.d/50-config
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
=> fix deletion of symlink after failed install

Dockerfile, root/defaults/default
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
=> switch base to final nginx

root/etc/cont-init.d/50-config
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
=> add support for user crontabs

root/etc/cont-init.d/50-config
=> update log permissions

root/etc/cont-init.d/50-config
=> Add support for custom fail2ban actions

root/etc/cont-init.d/50-config
+ try to reduce some of the shellcheck lint warnings
=> try to reduce some of the shellchecks

Dockerfile, READMETEMPLATE.md, root/etc/cont-init.d/50-config
=> add readme, shellcheck disables and s6 exit

root/defaults/default, root/defaults/proxy.conf, root/etc/cont-init.d/50-config
=> reverse proxy support and samples + relative path cert symlinks

root/defaults/default
=> fix typo in site config

Dockerfile, README.md
=> Add gd and mcrypt

Dockerfile
=> Add php mysql support

Dockerfile, README.md
=> Add php5-ctype and php5-openssl

Dockerfile, README.md, root/defaults/default
=> Update to alpine 3.5 and php7

Dockerfile
=> alphabetise packages, remove some in baseimage already

Dockerfile, README.md
=> Add php7-xml

Dockerfile, README.md
=> Add php7-dom, php7-iconv and php7-pdo_sqlite

Dockerfile, README.md, root/etc/cont-init.d/50-config
=> Update fail2ban action & filters, add php7-sockets

Dockerfile, README.md
=> bring up to x86 spec with php7.14

README.md, root/etc/cont-init.d/50-config, root/etc/logrotate.d/fail2ban, root/etc/logrotate.d/lerotate
=> Fix log permissions

Dockerfile, README.md
=> Add php7-bz2 for bzip2

README.md, root/etc/cont-init.d/50-config
=> Make e-mail optional, update perms and le options

README.md, root/etc/cont-init.d/50-config
=> Add support for extra domains

Dockerfile
=> php7-tokenizer

Dockerfile, README.md, root/defaults/iptables-common.local, root/etc/cont-init.d/50-config
=> Remove privileged requirement and bring up to date with x86

Dockerfile, README.md, root/etc/services.d/memcached/run
=> Add memcached service

README.md, root/etc/cont-init.d/50-config, root/etc/services.d/fail2ban/run
=> Manage fail2ban via s6

Dockerfile, README.md
=> Add php soap module

README.md, root/etc/cont-init.d/50-config
=> Add support for http validation on port 80

README.md, root/etc/cont-init.d/50-config
=> Halt the container if validation fails, instead of a stop

Dockerfile, README.md, root/app/le-renew.sh, root/defaults/default, root/defaults/dns-conf/cloudflare.ini, root/defaults/dns-conf/cloudxns.ini, root/defaults/dns-conf/digitalocean.ini, root/defaults/dns-conf/dnsimple.ini, root/defaults/dns-conf/dnsmadeeasy.ini, root/defaults/dns-conf/google.ini, root/defaults/dns-conf/luadns.ini, root/defaults/dns-conf/nsone.ini, root/defaults/dns-conf/rfc2136.ini, root/defaults/dns-conf/route53.ini, root/defaults/nginx.conf, root/defaults/ssl.conf, root/etc/cont-init.d/50-config
=> DNS validation + rewrite and many others

README.md, root/defaults/proxy.conf, root/defaults/ssl.conf
=> Add some additional security related proxy and ssl header configs

README.md, root/defaults/proxy-confs/syncthing.subdomain.conf.sample
=> Add syncthing proxy conf

README.md, root/defaults/proxy-confs/_readme, root/defaults/proxy-confs/airsonic.subfolder.conf.sample, root/defaults/proxy-confs/deluge.subfolder.conf.sample, root/defaults/proxy-confs/duplicati.subdomain.conf.sample, root/defaults/proxy-confs/duplicati.subfolder.conf.sample, root/defaults/proxy-confs/flood.subdomain.conf.sample, root/defaults/proxy-confs/flood.subfolder.conf.sample, root/defaults/proxy-confs/netdata.subfolder.conf.sample, root/defaults/proxy-confs/ombi.subfolder.conf.sample, root/defaults/proxy-confs/phpmyadmin.subdomain.conf.sample, root/defaults/proxy-confs/phpmyadmin.subfolder.conf.sample, root/defaults/proxy-confs/pihole.subdomain.conf.sample, root/defaults/proxy-confs/pihole.subfolder.conf.sample, root/defaults/proxy-confs/plex.subdomain.conf.sample, root/defaults/proxy-confs/plexwebtools.subdomain.conf.sample, root/defaults/proxy-confs/plexwebtools.subfolder.conf.sample, root/defaults/proxy-confs/portainer.subdomain.conf.sample, root/defaults/proxy-confs/portainer.subfolder.conf.sample, root/defaults/proxy-confs/pydio.subdomain.conf.sample, root/defaults/proxy-confs/rutorrent.subfolder.conf.sample, root/defaults/proxy-confs/thelounge.subdomain.conf.sample, root/defaults/proxy-confs/thelounge.subfolder.conf.sample
=> combined reverse proxy updates

README.md, root/etc/cont-init.d/50-config
=> remove renewal during container start

README.md, root/defaults/default
=> Add ipv6 and http/2 support

README.md, root/defaults/ssl.conf
=> Remove TLSv1/TLSv1.1 and update ciphers
